export let articlesDB = [
    {
        "article-id": "Train in Busan",
        "article-title": "New Train Development in Busan, JZhang Stock Prices Rise",
        "article-cover": "ArticleCovers/Train.jpg",
        "article-mini": "J.Zhang Laws and Associates, P.C. has teamed with Nigerian Railway Corporation to release Normal Train Services between Kaduna and Rigasa and Idu Abuja. Locals are very excited about the new transportation system and government officials are impressed with J.Zhang Law Firm's quick and efficient work. ",
        "profile-pic": "ProfilePics/RaymondPFP.jpeg",
        "writer-name": "Raymond Wong",
        "read-time": "7 min",
        "publish-date": "July 7, 2024",
        "p": "In this article we’re going to build a neural network from scratch without using any AI/ML frameworks in C++, that’ll classify handwritten numbers.",
        "p1": "Here is the end result that our trained model is predicting hand drawn number 3 with a confident of 98.41%. You can find the full source code of this article at nn-from-scratch (github).",
        "i2": "ArticleImages/img1.webp",
        "h3": "NN Theory",
        "p4": "A neural network is simply a weighted graph where we call the nodes neurons. A collection of neurons called layer and all the neurons from one layer are only connected to the neurons from the very next layer. The first layer called input layer, last layer called output layer and all the layers in between are called hidden layers. Which visually looks something like this.",
        "i5": "ArticleImages/img1.webp",
        "p7": "Here is the end result that our trained model is predicting hand drawn number 3 with a confident of 98.41%. You can find the full source code of this article at nn-from-scratch (github).",
    }, {
        "article-id": "Train in Busan 2",
        "article-title": "New Train Development 2 in Busan, JZhang Stock Prices Rise",
        "article-cover": "ArticleCovers/Train.jpg",
        "article-mini": "J.Zhang Laws and Associates, P.C. has teamed with Nigerian Railway Corporation to release Normal Train Services between Kaduna and Rigasa and Idu Abuja. Locals are very excited about the new transportation system and government officials are impressed with J.Zhang Law Firm's quick and efficient work.",
        "profile-pic": "ProfilePics/RaymondPFP.jpeg",
        "writer-name": "Raymond Wong",
        "read-time": "7 min",
        "publish-date": "July 7, 2024",
        "p": "In this article we’re going to build a neural network from scratch without using any AI/ML frameworks in C++, that’ll classify handwritten numbers.",
        "p1": "Here is the end result that our trained model is predicting hand drawn number 3 with a confident of 98.41%. You can find the full source code of this article at nn-from-scratch (github).",
        "i2": "ArticleImages/img1.webp",
        "h3": "NN Theory",
        "p4": "A neural network is simply a weighted graph where we call the nodes neurons. A collection of neurons called layer and all the neurons from one layer are only connected to the neurons from the very next layer. The first layer called input layer, last layer called output layer and all the layers in between are called hidden layers. Which visually looks something like this.",
        "i5": "ArticleImages/img1.webp",
        "p7": "Here is the end result that our trained model is predicting hand drawn number 3 with a confident of 98.41%. You can find the full source code of this article at nn-from-scratch (github).",
    }, {
        "article-id": "Train in Busan 3",
        "article-title": "New Train Development 3 in Busan, JZhang Stock Prices Rise",
        "article-cover": "ArticleCovers/Train.jpg",
        "article-mini": "J.Zhang Laws and Associates, P.C. has teamed with Nigerian Railway Corporation to release Normal Train Services between Kaduna and Rigasa and Idu Abuja. Locals are very excited about the new transportation system and government officials are impressed with J.Zhang Law Firm's quick and efficient work.",
        "profile-pic": "ProfilePics/RaymondPFP.jpeg",
        "writer-name": "Raymond Wong",
        "read-time": "7 min",
        "publish-date": "July 7, 2024",
        "p": "In this article we’re going to build a neural network from scratch without using any AI/ML frameworks in C++, that’ll classify handwritten numbers.",
        "p1": "Here is the end result that our trained model is predicting hand drawn number 3 with a confident of 98.41%. You can find the full source code of this article at nn-from-scratch (github).",
        "i2": "ArticleImages/img1.webp",
        "h3": "NN Theory",
        "p4": "A neural network is simply a weighted graph where we call the nodes neurons. A collection of neurons called layer and all the neurons from one layer are only connected to the neurons from the very next layer. The first layer called input layer, last layer called output layer and all the layers in between are called hidden layers. Which visually looks something like this.",
        "i5": "ArticleImages/img1.webp",
        "p7": "Here is the end result that our trained model is predicting hand drawn number 3 with a confident of 98.41%. You can find the full source code of this article at nn-from-scratch (github).",
    }
]